#!/bin/sh
#
# wifi widget

n=4

iw=$(iwconfig 2>/dev/null | grep "Link Quality")
quality=$(echo $iw | awk '{ gsub(/[=/]/, " "); print $3 }')
max=$(echo $iw | awk '{ gsub(/[=/]/, " "); print $4 }')

if [[ -n $max ]]; then
  p=$[n - quality * l / max]
  echo "$(panel_progress $n $p)"
else
  echo ""
fi

