#!/bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
while true; do
  echo "S$(date "+%b %d, %I:%M %p")"
  echo "L$(panel_layout)"
  echo "I$(panel_wifi)"
  echo "C$(panel_charge)"
  if [[ -e `which ncmpcpp` && -n `ps -e |grep -w mpd` ]]; then
    echo "M$(ncmpcpp --now-playing | sed "s/(.*) //")"
  else
    echo "M"
  fi
  sleep 0.5;
done > "$PANEL_FIFO" &
# xtitle -sf 'T%s' > "$PANEL_FIFO" &
# clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

. panel_colors

case "$flavor" in
  bar)
    PANEL_HEIGHT="17"
    #FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
    FONT_FAMILY='-*-lemon-*-*-*-*-*-*-*-*-*-*-*-*'
    cat "$PANEL_FIFO" | panel_bar | bar -g x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
    ;;
  dzen2)
    FONT_FAMILY='DejaVu Sans'
    FONT_SIZE=11
    cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
    ;;
esac

wait

