#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

while read -r line ; do
  case $line in
    C*)
      if [[ -n ${line#?} ]]; then
        charge="%{F$COLOR_FOREGROUND}charge ${line#?}%{F$COLOR_FOREGROUND} · "
      else
        charge=""
      fi
      ;;
    I*)
      if [[ -n ${line#?} ]]; then
        wifi="%{F$COLOR_FOREGROUND}wifi ${line#?}%{F$COLOR_FOREGROUND} · "
      else
        wifi="%{F$COLOR_FOREGROUND}no wifi · "
      fi
      ;;
    L*)
      layout="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?} · "
      ;;
    M*)
      if [[ -n ${line#?} ]]; then
        now_playing="%{B$COLOR_TITLE_BG}%{F$COLOR_FREE_FG}♫ ${line#?}"
      else
        now_playing=""
      fi
      ;;
    S*)
      # clock output
      time="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?}"
      ;;
    T*)
      # xtitle output
      title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        entry=""
        case $item in
          O*)
            # focused occupied desktop
            entry="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}▪%{-u}"
            ;;
          F*)
            # focused free desktop
            entry="%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}▫%{-u}"
            ;;
          U*)
            # focused urgent desktop
            entry="%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}▩%{-u}"
            ;;
          o*)
            # occupied desktop
            entry="%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}▪"
            ;;
          f*)
            # free desktop
            entry="%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}▫"
            ;;
          u*)
            # urgent desktop
            entry="%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}▩"
            ;;
          #L*)
          #  # layout
          #  layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
          #  wm_infos="$wm_infos    %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG}$layout"
          #  ;;
        esac
        wm_infos="$wm_infos$entry "
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l} $wm_infos %{c}$now_playing $title %{r} $charge$wifi$layout$time "
done
