#!/bin/sh
#
# wifi widget

. panel_colors

n=$1
p=$2
q=$[n-p]

result="%{F$COLOR_ACTIVE_FG}"

for i in `seq 1 $p`; do
  result="$result-"
done

result="$result%{F$COLOR_PASSIVE_FG}"

for i in `seq 1 $q`; do
  result="$result-"
done

echo $result

