#!/usr/bin/env zsh

alias s="sudo"
alias v="nvim"
alias grep="grep --color=auto"
alias df="df -h"
alias du="du -h"
alias ls="ls --color"
alias la="ls -a"
alias lla="ls -la"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias c="docker-compose"
alias session="tmux new-session -s"
alias tcd="tmux attach-session -c"

function mkdircd {
  mkdir -p "$1" && cd "$1";
}

# platform specific `ls` alias
if [[ $platform == 'linux' ]]; then
  alias ls='ls --color=auto'
elif [[ $platform == 'freebsd' || $platform == 'macos' ]]; then
  alias ls='ls -G'
fi

# git aliases
# 'g' alias for git
function g {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status --short --branch
  fi
}

compdef g='git'

function __ch_try() {
  local branch_name=$(git branch --list | grep "$1" | head -n 1)
  if [[ -n "$branch_name" ]]; then
    git checkout "${branch_name:2:1000}"
    echo 1
  fi
}

function ch() {
  local name="$1"
  local result=$(__ch_try "$CH_PREFIX-$name")
  if [[ -z "$result" ]]; then
    result=$(__ch_try "$name")
  fi
  if [[ -z "$result" ]]; then
    echo "Can't find branch"
    return 1
  fi
}

alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias ga="git add --all "
alias gc="git commit -m "
alias go="git checkout "
alias rebase-onto-master="git fetch && git rebase origin/master"
alias commits-by-author="git shortlog --summary --numbered --all --no-merges"
alias root='cd $(git rev-parse --show-cdup)'

# config files aliases
function conf {
  case "$1" in
    zsh )
      nvim ~/.zshrc
      ;;
    "zsh.aliases" )
      nvim ~/.zsh.d/aliases
      ;;
    vim | nvim )
      nvim ~/.vim/nvimrc
    ;;
  esac
}
alias zshconf="nvim ~/.zshrc"
alias zshdconf="nvim ~/.zsh.d"
