#!/bin/bash

http_server() {
  python3 -m http.server $1
}

samba_server() {
  target=$(cd ${1-.}; pwd)
  echo $target
  docker run -it -p 137-139:137-139 -p 445:445 --rm -v "$target":/shared --name samba pwntr/samba-alpine
}

case "$1" in
  "samba" )
    samba_server $2 ;;
  "http" )
    http_server $2 ;;
  "--help" )
    echo -e "usage: serve [http] <port>\n       serve samba" ;;
  * )
    http_server $1 ;;
esac

