#!/bin/bash
# Usage: aur package_name
# Builds and installs given AUR package

PACKAGE=$1
TMP="/tmp/aur"

function error { echo -e 2>&1 "\e[91m==> ERROR:\e[0m $1"; exit 1; }
function info { echo -e 2>&1 "\e[92m==>\e[0m $1"; }

if [ -d $TMP ]; then
  error "Seems like aur is already running (/tmp/aur exists)."
fi

if ! hash makepkg 2>/dev/null; then
  error "No makepkg found."
fi

if [ -z $PACKAGE ]; then
  error "No package specified."
fi

trap "rm -rf $TMP" SIGHUP SIGINT SIGTERM

mkdir $TMP && cd $TMP
info "Retrieving PKGBUILD for $PACKAGE..."
curl -# https://aur.archlinux.org/packages/${PACKAGE:0:2}/$PACKAGE/$PACKAGE.tar.gz > $PACKAGE.tar.gz &&
  (tar -xvf $PACKAGE.tar.gz >/dev/null 2>&1 || error "Package doesn't exist.") &&
  cd $PACKAGE && makepkg -si

rm -rf $TMP

